### ISSUE TITLE
Realm ne supporte pas 'l'héritage

### ISSUE THREAD

**Issue by armandooj** [armandooj/VirginiaBeach#1]
Je viens de le découvrir : [GitHub issue](https://github.com/realm/realm-java/issues/761). Ils sont en train de l'implémenter mais pour l'instant cela ne marche pas. La mauvaise nouvelle c'est que j'avais déjà écris mes modèles avec héritage.

Qu'en pensez-vous ?. Une solution serait d'utiliser composition ou simplement changer les modèles à une version sans héritage.

**Comment by GeeAie** [comment]
Oui tu peux faire une composition si ça ne pose pas de problème avec ton parsing GSON.
Sinon tu peux retirer l'héritage et passer par des interfaces.
Essaie de faire au plus simple.

**Comment by armandooj** [comment]
Ok, j'ai fait ça : le plus simple. J'ai passé à un seul objet avec un attribut pour spécifier le type. Cela a beaucoup simplifié les choses.
