### ISSUE TITLE
Questions sur les webservices

### ISSUE THREAD

**Issue by armandooj** [armandooj/VirginiaBeach#2]
Tout marche bien mais je crois qu'on pourrait améliorer quelques choses :

1. Il faut lancer une requête pour les restaurants et une autre pour les attractions. Est-il nécessaire de le faire comme cela ?. Dans ce moment c'est le client qui les lance séparément, les mets ensemble et les trie. Cela prend quelques secondes et pourrait être quasi-instantanée si on le faisait côté serveur.

2. Pour les attributs description et image, quand l'attribut est vide le serveur retourne un tableau vide : 
```
image: [ ],
```
mais dans le cas où il y a quelque chose il retourne un seul élément : 
```
image: {
   file: {
      uri: "http://virginia.mobyview.eu/api/entity_file/990",
      ...
   }
},
```
J'utilise gson pour la désérialisation et cela ne marche pas avec les attributs qui changent de type dynamiquement (comme de tableau à élément json). Pouvons-nous retourner null simplement ?. Sinon, je vais trouver une solution de contournement.

**Comment by GeeAie** [comment]
1. Malheurement, sur cette version, il n'est pas possible de le faire coté serveur. Tu dois gérer les 2 requêtes coté client... fait comme tu peux.
2. Oui j'ai vu qu'il n'y avait pas d'image sur certains contenus, comme sur le point 1, je ne peux pas faire de modif sur le serveur.

**Comment by armandooj** [comment]
Ok, ça marche. Je l'ai fait côté client :)
