### ISSUE TITLE
Taille et nomenclature des images sur Android

### ISSUE THREAD

**Issue by armandooj** [armandooj/VirginiaBeach#3]
Cela serait très apprécié de suivre les conventions : [Android Cheatsheet for Graphic Designers](http://petrnohejl.github.io/Android-Cheatsheet-For-Graphic-Designers/).

Sur Android, par exemple, on n'utilise pas le @2x, @3x, etc., mais des dossiers différents pour chaque taille. 

J'ai auto-généré les icônes à partir de la plus grand mais si on veut que cela soit parfait, je vais avoir besoin de les 5 versions.

Pour les spécifications des certains éléments qui étaient en px, j'ai utilisé l'équivalent (plus ou moins) en dp (Density-independent Pixels). Ce n'est pas recommandé d'utiliser px à cause du grand nombre des tailles des écrans qui utilisent Android.

Et finalement, pour le splash. J'ai coupé et centré le logo dans un rectangle de la même couleur. 

Question. Où devons-nous utiliser le "Overlay-img-detail.png" ?
Et pour le reste, on le laisse comme cela ou on change quelque chose ?

**Comment by BaptisteManchon** [comment]
Vous pouvez utiliser les assets en .svg pour android.
l'"Overlay-img-detail.png" doit être par dessus l'image dans les pages de detail, il permet de mieux voir le texte blanc sur l'image.
Pas de problème pour le reste.
